
export const featureOptions = [
  { key: 'Features - Private Terrace', label: 'Private Terrace' },
  { key: 'Climate Control - Air Conditioning', label: 'Air Conditioning' },
  { key: 'Kitchen - Fully Fitted', label: 'Fully Fitted Kitchen' },
  { key: 'Features - Fitted Wardrobes', label: 'Fitted Wardrobes' },
  { key: 'Setting - Close To Shops', label: 'Close To Shops' },
  { key: 'Features - Covered Terrace', label: 'Covered Terrace' },
  { key: 'Setting - Close To Schools', label: 'Close To Schools' },
  { key: 'Orientation - South', label: 'South Facing' },
  { key: 'Views - Sea', label: 'Sea Views' },
  { key: 'Condition - Excellent', label: 'Excellent Condition' },
  { key: 'Features - Fiber Optic', label: 'Fiber Optic' },
  { key: 'Views - Mountain', label: 'Mountain Views' },
  { key: 'Setting - Close To Sea', label: 'Close To Sea' },
  { key: 'Pool - Communal', label: 'Communal Pool' },
  { key: 'Pool - Private', label: 'Private Pool' },
  { key: 'Security - Gated Complex', label: 'Gated Complex' },
  { key: 'Setting - Close To Town', label: 'Close To Town' },
  { key: 'Features - Ensuite Bathroom', label: 'Ensuite Bathroom' },
  { key: 'Features - Storage Room', label: 'Storage Room' },
  { key: 'Features - Near Transport', label: 'Near Transport' },
  { key: 'Features - Double Glazing', label: 'Double Glazing' },
  { key: 'Parking - Private', label: 'Private Parking' },
  { key: 'Parking - Communal', label: 'Communal Parking' },
];
