
export const featureOptions = [
  { key: 'Features - Private Terrace', label: 'Privat terrass' },
  { key: 'Climate Control - Air Conditioning', label: 'Luftkonditionering' },
  { key: 'Kitchen - Fully Fitted', label: 'Fullt utrustat kök' },
  { key: 'Features - Fitted Wardrobes', label: 'Inbyggda garderober' },
  { key: 'Setting - Close To Shops', label: 'Nära affärer' },
  { key: 'Features - Covered Terrace', label: 'Täckt terrass' },
  { key: 'Setting - Close To Schools', label: 'Nära skolor' },
  { key: 'Orientation - South', label: 'Söderläge' },
  { key: 'Views - Sea', label: 'Havsutsikt' },
  { key: 'Condition - Excellent', label: 'Utmärkt skick' },
  { key: 'Features - Fiber Optic', label: 'Fiberoptik' },
  { key: 'Views - Mountain', label: 'Bergsutsikt' },
  { key: 'Setting - Close To Sea', label: 'Nära havet' },
  { key: 'Pool - Communal', label: 'Gemensam pool' },
  { key: 'Pool - Private', label: 'Privat pool' },
  { key: 'Security - Gated Complex', label: 'Gated community' },
  { key: 'Setting - Close To Town', label: 'Nära stan' },
  { key: 'Features - Ensuite Bathroom', label: 'Eget badrum' },
  { key: 'Features - Storage Room', label: 'Förråd' },
  { key: 'Features - Near Transport', label: 'Nära kollektivtrafik' },
  { key: 'Features - Double Glazing', label: 'Tvåglasfönster' },
  { key: 'Parking - Private', label: 'Privat parkering' },
  { key: 'Parking - Communal', label: 'Gemensam parkering' },
];
